version: 0.2

phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install
      - npm install -g serverless
  post_build:
    commands:
      - serverless deploy --region us-east-1 --verbose